<?php

/**
 * @file
 * Contains \Drupal\micro\MicroEntityAccessController.
 */

namespace Drupal\micro;

use Drupal\Core\Entity\EntityAccessController;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

class MicroEntityAccessController extends EntityAccessController {

  /**
   * Performs access checks.
   */
  protected function checkAccess(EntityInterface $entity, $operation, $langcode, AccountInterface $account) {
    $access = parent::checkAccess($entity, $operation, $langcode, $account);

    if (!$access) {
      switch ($operation) {
        case 'view':
          $permission = 'view micro - ' . $entity->bundle() . ' entity';
          break;
        default:
          $permission = 'administer micro - ' . $entity->bundle() . ' entity';
          break;
      }

      return $account->hasPermission($permission);
    }

    return $access;
  }

  /**
   * Performs create access checks.
   */
  protected function checkCreateAccess(AccountInterface $account, array $context, $entity_bundle = NULL) {
    $access = parent::checkCreateAccess($account, $context, $entity_bundle); // TODO: Change the autogenerated stub
    if ($access) {
      return $access;
    }

    return $account->hasPermission('administer micro - ' . $entity_bundle . ' entity');
  }


}
